const commonContent = {
  greet: "Hi, ",
  username: "Username",
  password: "Password",
  appName: "Flashcard App",
  back: "Go Back",
  cancel: "Cancel",
  correct: "Remembered",
  createAccount: "Create an account",
  delete: "Delete",
  deleteConfirmation: "Are you sure you want to delete this card?",
  deleteSet: "Delete Set",
  deleteSetConfirmation: "Are you sure you want to delete this set?",
  edit: "Save",
  editAll: "Save All",
  endSessionConfirmation: "Are you sure you want to end the session?",
  incorrect: "Forgotten",
  loading: "Loading...",
  login: "Log in",
  logout: "Log Out",
  notRegisteredQuestion: "New to Flashcard App?",
  notmatch: "Password do not match",
  placeholderConfirmPassword: "Enter confirm password here...",
  placeholderDefinition: "Type definition here...",
  placeholderDescription: "Type description here...",
  placeholderPassword: "Enter password here...",
  placeholderTerm: "Type term here...",
  placeholderTitle: "Type title here...",
  placeholderUsername: "Enter username here...",
  proceed: "Proceed",
  registeredQuestion: "Already have an account?",
  register: "Register",
  required: "This is a required field",
  review: "Result",
  study: "Study",
};

export default commonContent;
